### ISSUE TITLE
warning: variant is never used: `Quit`

### ISSUE THREAD

**Issue by whimboo** [mozilla/webdriver-rust#112]
This seems to have been introduced lately and which is causing a compiler warning:

warning: variant is never used: `Quit`
  --> src/server.rs:23:5
   |
23 |     Quit
   |     ^^^^
   |
   = note: #[warn(dead_code)] on by default

The `Ok` case is already handled in line 63, so we never reach line 88:
https://github.com/mozilla/webdriver-rust/blob/master/src/server.rs#L63-L88

**Comment by jgraham** [comment]
This is a longstanding warning. It will probably go away if we implement signal handling using the chan-signal crate.

**Comment by whimboo** [comment]
Interesting because AFAIR I haven't seen it when compiling geckodriver lately with webdriver-rust 0.27. Maybe I don't remember correctly.

**Comment by whimboo** [comment]
Ok, so this indeed goes back way longer. Thanks for mentioning this James.

**Comment by andreastt** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1396820.
