### ISSUE TITLE
Proxy configuration object missing noProxy key

### ISSUE THREAD

**Issue by andreastt** [mozilla/webdriver-rust#120]
The proxy configuration object is missing the `noProxy` key:

> Lists the address for which the proxy should be bypassed when the proxyType is "manual".

It is supposed to be

> A List containing any number of any of domains, IPv4 addresses, or IPv6 addresses.

**Comment by andreastt** [comment]
cc @whimboo

**Comment by whimboo** [comment]
It's something I work on issue #108.
