### ISSUE TITLE
Update wording for expected values in validity checks

### ISSUE THREAD

**Issue by whimboo** [mozilla/webdriver-rust#122]
As requested by @andreastt on https://github.com/mozilla/webdriver-rust/pull/121#discussion_r136056905:

```
Generally we should avoid passive language in error messages, and I think we could afford to be a tad more specific regarding which key this applies to.

I suggest: `Expected noProxy to be an array, got: {}.`
```

We should check for which keys this wording can be used.

**Comment by andreastt** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1396819.
