### ISSUE TITLE
Use unicode-segmentation to process grapheme clusters in key actions

### ISSUE THREAD

**Issue by mjzffr** [mozilla/webdriver-rust#59]
Right now only single characters for key "value" are accepted when parsing message body for key actions, which means we error out when a valid grapheme cluster is sent in. (Example: tamil nadu char `"\u0BA8\u0BBF"`). 

Apparently this unicode-segmentation library can be used to determine whether a string is a single grapheme cluster.

**Comment by andreastt** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1396823.
