### ISSUE TITLE
Error response body specified incorrectly

### ISSUE THREAD

**Issue by jugglinmike** [mozilla/webdriver-rust#63]
Currently, error responses are specified in the HTTP response's "top-level" JSON object. However, the latest draft of the WebDriver specification reads:

> 4. [...] Let data be a new JSON Object initialised with the following
>    properties:
>
>    - error  
>        - name  
>    - message  
>        - message  
>    - stacktrace  
>        - stacktrace
>
> 5. Send a response with status and data as arguments.

Where "send a response" includes the following step:

> 4. If data is not null, let response’s body be a JSON Object with a key value
>    set to the JSON Serialization of data. 

For example, currently, an HTTP response for a WebDriver error might look like this:

```json
{
  "error": "no such window",
  "message": "No such content frame; perhaps the listener was not registered?"
}
```

But according to the specification, it should actually be formatted as follows:

```json
{
  "value": {
    "error": "no such window",
    "message": "No such content frame; perhaps the listener was not registered?"
  }
}
```

**Comment by jugglinmike** [comment]
In addition, the result does not specify a `stacktrace` property. Although the specification describes this value as "implementation-defined," it's presence is not optional. An empty string would seem to satisfy the requirements (although not many users).

**Comment by andreastt** [comment]
This is in part https://github.com/mozilla/geckodriver/issues/261 (coming from the recent decision to encapsulate everything in a `value` field as of https://github.com/w3c/webdriver/pull/345), but it’s good to keep an issue for tracking this also in webdriver-rust.

It’s a known issue that we don’t return everything inside a `value` field yet, but I’m quite sure Marionette always returns a `stacktrace` field. It’s surprising that geckodriver/webdriver-rust isn’t preserving it as it gets returned to the client.

**Comment by andreastt** [comment]
It looks like it’s only the errors originating from the Rust code itself that is missing the `stacktrace` field. The stacktraces from Marionette are propagated without modification.
