### ISSUE TITLE
"move" and "cancel" should be "pointerMove" and "pointerCancel"

### ISSUE THREAD

**Issue by mjzffr** [mozilla/webdriver-rust#68]
...to match the spec. 

I'm hitting the following error when I send messages that specify "pointerMove" as the subtype, for example: https://github.com/mozilla/webdriver-rust/blob/7ec65451c99b638655c72e7b9718a374ff60de87/src/command.rs#L1492-L1493

**Comment by andreastt** [comment]
Patch in https://github.com/mozilla/webdriver-rust/pull/69 for visibility.
