### ISSUE TITLE
proxyType should be case insensitive

### ISSUE THREAD

**Issue by andreastt** [mozilla/webdriver-rust#86]
According to https://github.com/w3c/webdriver/pull/870, the `proxyType` field should be case insensitive.

**Comment by jgraham** [comment]
I think that spec change is a mistake.

**Comment by whimboo** [comment]
@jgraham, @andreastt so how should we go on with this issue?

CC @shs96c and @AutomatedTester

**Comment by shs96c** [comment]
Didn't we roll back the spec change and implement the fix on the local end side.

**Comment by whimboo** [comment]
Oh, I'm fine then. Maybe I was only confused by the referenced PR which got landed, but no mention of backing it out.

It means that we can close this issue. Thanks.
