### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [mozilla/webdriver-rust#93]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by andreastt** [comment]
We have wanted to move to serde for some time, but have been awaiting it to become usable with Rust stable. Unfortunately, moving from rustc-serialize to serde is not entirely trivial, but it is very much on our radar.

**Comment by jgraham** [comment]
Opening issues on dozens of repos because of a deprecation announcement is unnecessary and spammy . We are aware of the status of rustc_serialize and also of how migrating a major part of the code fits in with our other priorities. We even have a (bitrotted) experimental branch.

**Comment by dtolnay** [comment]
Thanks for the feedback @jgraham. Canvassing with issues is a great way to expose dependencies like "I can't because hyper" or "I can't because Cargo" or "I can't because of obscure feature X in rustc_serialize" or "I can't because I don't understand this part of the docs," and that helps me prioritize what and where I contribute to be maximally valuable to the ecosystem. So it isn't about dictating what your prioritization should be, I apologize for implying that.

Is there a different issue already tracking this that I could follow?

**Comment by jgraham** [comment]
OK. I detailed the current status in #94.
