### ISSUE TITLE
Use serde in place of rustc_serialize

### ISSUE THREAD

**Issue by jgraham** [mozilla/webdriver-rust#94]
In the long term it would be a good idea to use serde instead of rustc_serialize. This will allow us to derive a lot of the implementation from the struct definitions, and should remove a great deal of boilerplate code dealign with type conversions and errors. The serde branch contains a (bitrotted) first attempt at this; it seemed mostly straightforward except for the actions API where the internal representation uses a different struct based on the `action` field of the message; it wasn't entirely clear to me how to map that using any of the provided attributes so it's probably necessary to write some custom derive/serialize logic for those parts (or deserialize to a struct that matches the protocol and then convert that into the form that matches the data model).

This transition should also be accompanied by some improved tests for the low level parts of the protocol to ensure that we don't regress existing behaviour.

**Comment by dtolnay** [comment]
Thanks @jgraham! I didn't find the place in the code dealing with `action` but I think Serde's [internally tagged enum](https://serde.rs/enum-representations.html#internally-tagged) may be what you need.

```rust
extern crate serde;

#[macro_use] extern crate serde_json;
#[macro_use] extern crate serde_derive;

use serde::Deserialize;

#[derive(Deserialize, Debug)]
#[serde(tag = "action", rename_all = "lowercase")]
enum Action {
    Smile(Smile),
    Frown { muscles: u16 },
}

#[derive(Deserialize, Debug)]
struct Smile {
    seconds: u64,
}

fn main() {
    let smile = json!({ "action": "smile", "seconds": 2 });
    println!("{:?}", Action::deserialize(smile).unwrap());

    let frown = json!({ "action": "frown", "muscles": 11 });
    println!("{:?}", Action::deserialize(frown).unwrap());
}
```

**Comment by jgraham** [comment]
Ah, that does look useful indeed. Thanks!

**Comment by jgraham** [comment]
So it seems that we are also missing https://github.com/serde-rs/serde/issues/119

The problem is that we have something that looks like:

``` json
{"id": null,
 "type": "pointer",
 "parameters": {"pointerType": "mouse"},
 "actions": […]}
```
or
``` json
{"id": null,
 "type": "key",
 "actions": […]}
```

So parameters can only exist for the mouse-type actions. So this is modelled as a set of nested enums:

``` rust
enum ActionsSequence {
    id: Option<String>,
    actions: ActionsType
}

enum ActionsType {
    Key(Vec<KeyActions>),
    Pointer {parameters: PointerParameters, Vec<PointerActions>}
}
```

So obviously what's needed is to be able to flatten the `ActionsType` enum into the `ActionsSequence`, but that currently seems to  be difficult.

**Comment by dtolnay** [comment]
Here is how I would handle it. (Or contribute a flatten implementation!)

```rust
impl<'de> Deserialize<'de> for ActionsSequence {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer<'de>
    {
        #[derive(Deserialize)]
        #[serde(tag = "type", rename_all = "lowercase")]
        enum Helper {
            Key {
                id: Option<String>,
                actions: Vec<KeyActions>,
            },
            Pointer {
                id: Option<String>,
                parameters: PointerParameters,
                actions: Vec<PointerActions>,
            },
        }

        match Helper::deserialize(deserializer)? {
            Helper::Key { id, actions } => {
                Ok(ActionsSequence {
                    id: id,
                    actions: ActionsType::Key(actions),
                })
            }
            Helper::Pointer { id, parameters, actions } => {
                Ok(ActionsSequence {
                    id: id,
                    actions: ActionsType::Pointer(parameters, actions),
                })
            }
        }
    }
}
```

**Comment by whimboo** [comment]
@jgraham what do you think about the proposal from @dtolnay?

**Comment by jonhoo** [comment]
It'd be great to see some progress on this so we can drop the dependency on the deprecated `rustc-serialize`

**Comment by andreastt** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1396821.
