### ISSUE TITLE
Current session ID is exposed when providing unknown session ID

### ISSUE THREAD

**Issue by andreastt** [mozilla/webdriver-rust#98]
As reporetd by @fluffysquirrels in https://github.com/mozilla/geckodriver/issues/758#issuecomment-304986866:

```sh
 % curl -sS http://localhost:4444/session/foo/url | jq '.'
{
  "value": {
    "error": "invalid session id",
    "message": "Got unexpected session id foo expected 1687e068-15c4-4157-a8d4-2fcdd497bd84",
    "stacktrace": "[...]" // Skipped for length
  }
}
```

[This](https://github.com/mozilla/webdriver-rust/blob/master/src/server.rs#L108-L110) looks like the code in webdriver-rust that generates the message.

We should not expose the current session ID when we don’t have a session with the requested ID.

**Comment by jgraham** [comment]
@whimboo want to try fixing this one? I can do it if not.

**Comment by whimboo** [comment]
I would but won't have time for it. So if you can that would be great.
